CLDC-2359 Do not allow 32 as an option for 22/23 sale type
communitiesuk/submit-social-housing-lettings-and-sales-data pull request #1631
Opened 2023-05-16 07:50 UTC by kosiakkatrina

2023-05-18 16:33 UTC, asmega commented on spec/services/bulk_upload/sales/year2023/row_parser_spec.rb
> +          expect(log["type"]).to eq(32)
log should be an activerecord object. can you therefore not use `log.type`?

2023-05-18 16:35 UTC, asmega commented
if its not a valid option would `validate_valid_radio_option` not clear it?

2023-05-19 10:00 UTC, kosiakkatrina commented
> if its not a valid option would `validate_valid_radio_option` not clear it?

@asmega I think it wouldn't cause it's a valid option in one of the years (?)

2023-05-19 10:01 UTC, kosiakkatrina commented on spec/services/bulk_upload/sales/year2023/row_parser_spec.rb
> +          expect(log["type"]).to eq(32)
Yup!

2023-05-22 07:58 UTC, natdeanlewissoftwire approved these changes
lgtm :) (although I also would have expected 32 to be cleared by `validate_valid_radio_option`)

update - I've just checked and it looks like it is being cleared, but because the error is in the setup section the log is created with only the setup section in progress...  I think actually there's a bug in some of the row parsers that are checking `if errors[field].present?`, I believe they should actually be `unless errors[field].present?` e.g. the sales 22 row parser, but look like it's not alone.

2023-05-22 08:17 UTC, natdeanlewissoftwire requested changes
changing to request changes according to my update above, happy to be wrong but would like to work it out first!

2023-05-22 09:02 UTC, natdeanlewissoftwire approved these changes

2023-05-22 10:53 UTC, merged