Add owning organisation filter
communitiesuk/submit-social-housing-lettings-and-sales-data pull request #1772
Opened 2023-07-13 09:27 UTC by kosiakkatrina

2023-07-13 12:56 UTC, jackscotti approved these changes

2023-07-13 12:57 UTC, ghost approved these changes

2023-07-13 13:07 UTC, ghost commented
<img width="327" alt="Screenshot 2023-07-13 at 15 07 10" src="https://github.com/communitiesuk/submit-social-housing-lettings-and-sales-data/assets/113976590/67f50c9d-8211-4454-93b6-ee5e4af9a03a">
@kosiakkatrina should say "Owned by"

2023-07-13 13:07 UTC, ghost requested changes
see my last comment, filter label different from design

2023-07-13 13:22 UTC, ghost commented on app/views/logs/_log_filters.html.erb
> +         <% if @current_user.support? || @current_user.organisation.has_stock_owners? && request.path == "/lettings-logs" %>
AC: Only show this filter on the Lettings page to support users and organisations with **more than one** stock owner

2023-07-13 13:30 UTC, ghost commented on app/views/logs/_log_filters.html.erb
> +              "all": { label: "All" },
incorrect label
<img width="210" alt="Screenshot 2023-07-13 at 15 29 53" src="https://github.com/communitiesuk/submit-social-housing-lettings-and-sales-data/assets/113976590/38f7df89-8ecc-467d-8efc-3964c93dcad3">

2023-07-13 13:31 UTC, ghost commented on app/views/logs/_log_filters.html.erb
> +            label: "Owning organisation",
should say "owned by"

2023-07-14 09:02 UTC, kosiakkatrina commented on app/views/logs/_log_filters.html.erb
> +              "all": { label: "All" },
yes! Good point, didn't realise there were designs 😅

2023-07-14 10:31 UTC, ghost approved these changes

2023-07-17 14:13 UTC, ghost approved these changes

2023-07-17 14:29 UTC, merged