CLDC-771: Allow Data Coordinator to change details for users in their organisation
communitiesuk/submit-social-housing-lettings-and-sales-data pull request #428
Opened 2022-03-28 10:50 UTC by baarkerlounger

For users in their organisation Data Coordinators can:

- Update name
- Update email
- Update role

They cannot update password (only the user themselves can do that). (Though they technically could update email and use that to reset password).

2022-03-28 13:16 UTC, kosiakkatrina approved these changes

2022-03-28 16:24 UTC, paulrobertlloyd requested changes

2022-03-28 16:24 UTC, paulrobertlloyd commented on app/views/users/edit.html.erb
> +
Use Yes/No radios rather than a checkbox

2022-03-28 16:24 UTC, paulrobertlloyd commented on app/views/users/new.html.erb
> +
Ditto

2022-03-28 16:24 UTC, paulrobertlloyd commented on app/views/users/show.html.erb
> +        row.action(visually_hidden_text: 'are they a data protection officer?', href: edit_user_path, html_attributes: { 'data-qa': 'change-are-they-a-data-protection-officer' })
Given that the visible label is ‘Change’, probably makes sense for this to say:

```suggestion
        row.action(visually_hidden_text: 'if they a data protection officer', href: edit_user_path, html_attributes: { 'data-qa': 'change-are-they-a-data-protection-officer' })
```

2022-03-29 08:14 UTC, baarkerlounger commented on app/views/users/show.html.erb
> +        row.action(visually_hidden_text: 'are they a data protection officer?', href: edit_user_path, html_attributes: { 'data-qa': 'change-are-they-a-data-protection-officer' })
Change "whether" they are a data protection officer? @Dan13L3 what's your preference?

2022-03-29 08:15 UTC, baarkerlounger commented on app/views/users/edit.html.erb
> +
Even though the answer will hardly ever be yes?

2022-03-29 08:30 UTC, baarkerlounger commented on app/views/users/edit.html.erb
> +
Done

2022-03-29 08:30 UTC, baarkerlounger commented on app/views/users/new.html.erb
> +
Done

2022-03-29 09:39 UTC, Dan13L3 commented on app/views/users/show.html.erb
> +        row.action(visually_hidden_text: 'are they a data protection officer?', href: edit_user_path, html_attributes: { 'data-qa': 'change-are-they-a-data-protection-officer' })
@baarkerlounger Can it be dynamic, so if someone's changing someone else's details, it's 'Are they a data protection officer?', and if it's their own, 'Are you a data protection officer?' (And then the label under personal details stays as 'Data protection officer'.)

2022-03-29 12:33 UTC, merged